// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $addPage from "./routes/addPage.tsx";
import * as $deletePage from "./routes/deletePage.tsx";
import * as $index from "./routes/index.tsx";
import * as $searchPage from "./routes/searchPage.tsx";
import * as $addHero from "./islands/addHero.tsx";
import * as $deleteHero from "./islands/deleteHero.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/addPage.tsx": $addPage,
    "./routes/deletePage.tsx": $deletePage,
    "./routes/index.tsx": $index,
    "./routes/searchPage.tsx": $searchPage,
  },
  islands: {
    "./islands/addHero.tsx": $addHero,
    "./islands/deleteHero.tsx": $deleteHero,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
